# Programming language definition
language: cpp

# Build matrix (OS, compiler)
matrix:
  include:
    - os: linux
      compiler: gcc
     
   

# Branches to build
branches:
  only:
    - master

# Scripts that run before install
before_install:
  # cmake
  - sudo apt-get update
  - sudo apt-get install -y build-essential
  - sudo apt-get install -y cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev
  - sudo apt-get install -y python-dev python-numpy libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev libdc1394-22-dev

  - cmake --version
  # git
  - git config --global user.name "Travis CI"
  - git config --global user.email "travis@travis-ci.org"
  - git config --global push.default simple
  # gcc

# Build scripts
script: 
  - mkdir build
  - cd build
  - cmake ..
  - make -j6

# Don't send notifications on success
notifications:
  email:
    on_success: never
