# Programming language definition
language: cpp

# Build matrix (OS, compiler)
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
            - g++-8
            - cmake
            - doxygen
            - graphviz
            - binutils-dev
            - uuid-dev
            - build-essential
            - libgtk2.0-dev
            - pkg-config
            - libavcodec-dev 
            - libavformat-dev 
            - libswscale-dev
# Using Trusty environment
sudo: required
dist: trusty

# Branches to build
branches:
  only:
    - master

# Scripts that run before install
before_install:
  # cmake
  - cmake --version
  # git
  - git config --global user.name "Travis CI"
  - git config --global user.email "travis@travis-ci.org"
  - git config --global push.default simple
  # gcc

# Build scripts
script: 
  - mkdir build
  - cd build
  - cmake ..
  - make -j6

# Don't send notifications on success
notifications:
  email:
on_success: never
